services:
  web:
    build: .
    container_name: django-library-api-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}

db:
  image: postgres:14-alpine
  container_name: django-library-api-db
  volumes:
    - postgres_data:/var/lib/postgresql/data/
  environment:
    POSTGRES_DB: library_db
    POSTGRES_USER: library_user
    POSTGRES_PASSWORD: admin123


volumes:
  postgres_data:
